eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  payment-service:
    endpoits:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/dopayment
  order-service:
    endpoits:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookorder
